"""Convert a persisted scikit-learn regressor to ONNX and validate it.

This script expects the artifacts generated by ``train_turbines_model.py``:

* ``best_turbines_model.joblib``: either a fitted estimator or a dictionary
  containing the fitted estimator under the ``model`` key.
* ``dataset_CC02.csv``: used only for validation; it is never modified.

The script exports a single float32 tensor with shape ``[None, n_features]``.
That interface is usually easier to map in inference runtimes such as CSense.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import onnx
import onnxruntime as ort
import pandas as pd
from skl2onnx import to_onnx
from sklearn.metrics import mean_absolute_error, mean_squared_error


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_MODEL_PATH = BASE_DIR / "best_turbines_model.joblib"
DEFAULT_DATASET_PATH = BASE_DIR / "dataset_CC02.csv"
DEFAULT_ONNX_PATH = BASE_DIR / "best_turbines_model.onnx"
DEFAULT_REPORT_PATH = BASE_DIR / "onnx_validation_report.json"

DEFAULT_FEATURES = [
    "MW_TG",
    "Humedad",
    "Presion",
    "Temp",
    "Viento",
    "Viento_cos",
    "Viento_sin",
    "VIGV",
]
DEFAULT_TARGET = "MW_ST"
DEFAULT_DATE_COLUMN = "fecha"
DEFAULT_TEST_SIZE = 0.20
DEFAULT_TARGET_OPSET = 19


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convierte un modelo scikit-learn joblib a ONNX y valida sus métricas."
    )
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL_PATH)
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_ONNX_PATH)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT_PATH)
    parser.add_argument("--opset", type=int, default=DEFAULT_TARGET_OPSET)
    parser.add_argument("--test-size", type=float, default=DEFAULT_TEST_SIZE)
    parser.add_argument(
        "--allow-metric-drift",
        action="store_true",
        help="No termina con error si ONNX y scikit-learn difieren más que la tolerancia.",
    )
    return parser.parse_args()


def load_artifact(path: Path) -> tuple[Any, list[str], str, dict[str, Any]]:
    if not path.is_file():
        raise FileNotFoundError(f"No se encontró el modelo: {path}")

    artifact = joblib.load(path)
    metadata: dict[str, Any] = {}

    if isinstance(artifact, dict):
        if "model" not in artifact:
            raise KeyError("El artefacto joblib es un diccionario pero no contiene la clave 'model'.")
        model = artifact["model"]
        features = list(artifact.get("features", DEFAULT_FEATURES))
        target = str(artifact.get("target", DEFAULT_TARGET))
        metadata = {
            key: value
            for key, value in artifact.items()
            if key != "model" and isinstance(value, (str, int, float, bool, list, dict, type(None)))
        }
    else:
        model = artifact
        features = list(getattr(model, "feature_names_in_", DEFAULT_FEATURES))
        target = DEFAULT_TARGET

    if not hasattr(model, "predict"):
        raise TypeError("El objeto cargado no implementa predict().")
    if not features:
        raise ValueError("La lista de variables predictoras está vacía.")

    return model, features, target, metadata


def load_validation_data(
    path: Path,
    features: list[str],
    target: str,
    test_size: float,
) -> tuple[pd.DataFrame, np.ndarray, dict[str, Any]]:
    if not path.is_file():
        raise FileNotFoundError(f"No se encontró el dataset: {path}")
    if not 0 < test_size < 1:
        raise ValueError("--test-size debe estar entre 0 y 1.")

    df = pd.read_csv(path)
    required = [*features, target]
    missing = sorted(set(required) - set(df.columns))
    if missing:
        raise ValueError(f"Faltan columnas requeridas en el dataset: {missing}")

    validation_info: dict[str, Any] = {"date_column_used": False}
    if DEFAULT_DATE_COLUMN in df.columns:
        df[DEFAULT_DATE_COLUMN] = pd.to_datetime(df[DEFAULT_DATE_COLUMN], errors="coerce")
        if df[DEFAULT_DATE_COLUMN].isna().any():
            raise ValueError("El dataset contiene fechas inválidas.")
        df = df.sort_values(DEFAULT_DATE_COLUMN, kind="stable").reset_index(drop=True)
        validation_info["date_column_used"] = True

    if df[required].isna().any().any():
        counts = df[required].isna().sum()
        raise ValueError(f"Se encontraron valores faltantes:\n{counts[counts > 0]}")

    split_index = int(len(df) * (1 - test_size))
    if split_index <= 0 or split_index >= len(df):
        raise ValueError("El tamaño del dataset no permite crear el conjunto de validación.")

    validation = df.iloc[split_index:]
    X = validation[features].astype(np.float32)
    y = validation[target].to_numpy(dtype=np.float64)

    if not np.isfinite(X.to_numpy()).all() or not np.isfinite(y).all():
        raise ValueError("El conjunto de validación contiene valores no finitos.")
    if np.any(y == 0):
        raise ValueError("MAPE no está definido porque el target contiene valores iguales a cero.")

    validation_info.update(
        {
            "dataset_rows": int(len(df)),
            "validation_rows": int(len(validation)),
            "split_index": split_index,
            "test_size": test_size,
        }
    )
    if validation_info["date_column_used"]:
        validation_info["validation_from"] = validation[DEFAULT_DATE_COLUMN].iloc[0].isoformat()
        validation_info["validation_until"] = validation[DEFAULT_DATE_COLUMN].iloc[-1].isoformat()

    return X, y, validation_info


def calculate_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float]:
    percentage_errors = np.abs(y_true - y_pred) / np.abs(y_true) * 100
    return {
        "mae_mw": float(mean_absolute_error(y_true, y_pred)),
        "rmse_mw": float(mean_squared_error(y_true, y_pred) ** 0.5),
        "mape_pct": float(percentage_errors.mean()),
        "within_1pct_pct": float(np.mean(percentage_errors < 1) * 100),
    }


def export_to_onnx(
    model: Any,
    sample: np.ndarray,
    output_path: Path,
    target_opset: int,
) -> None:
    converted = to_onnx(
        model,
        sample,
        target_opset=target_opset,
        initial_types=None,
    )
    onnx.checker.check_model(converted)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(converted.SerializeToString())


def predict_onnx(model_path: Path, X: np.ndarray) -> tuple[np.ndarray, dict[str, Any]]:
    session = ort.InferenceSession(
        str(model_path),
        providers=["CPUExecutionProvider"],
    )
    inputs = session.get_inputs()
    if len(inputs) != 1:
        raise RuntimeError(f"Se esperaba una entrada ONNX, pero el modelo tiene {len(inputs)}.")

    input_meta = inputs[0]
    raw_outputs = session.run(None, {input_meta.name: X.astype(np.float32, copy=False)})
    if not raw_outputs:
        raise RuntimeError("ONNX Runtime no devolvió resultados.")

    predictions = np.asarray(raw_outputs[0], dtype=np.float64).reshape(-1)
    if len(predictions) != len(X) or not np.isfinite(predictions).all():
        raise RuntimeError("Las predicciones ONNX son inválidas.")

    interface = {
        "input_name": input_meta.name,
        "input_type": input_meta.type,
        "input_shape": [str(value) for value in input_meta.shape],
        "output_names": [output.name for output in session.get_outputs()],
    }
    return predictions, interface


def main() -> None:
    args = parse_args()
    model, features, target, artifact_metadata = load_artifact(args.model)
    X_validation, y_validation, validation_info = load_validation_data(
        args.dataset,
        features,
        target,
        args.test_size,
    )

    X_array = X_validation.to_numpy(dtype=np.float32)
    sklearn_predictions = np.asarray(model.predict(X_validation), dtype=np.float64).reshape(-1)
    if len(sklearn_predictions) != len(y_validation) or not np.isfinite(sklearn_predictions).all():
        raise RuntimeError("Las predicciones de scikit-learn son inválidas.")

    export_to_onnx(model, X_array[:1], args.output, args.opset)
    onnx_predictions, onnx_interface = predict_onnx(args.output, X_array)

    sklearn_metrics = calculate_metrics(y_validation, sklearn_predictions)
    onnx_metrics = calculate_metrics(y_validation, onnx_predictions)
    absolute_prediction_delta = np.abs(sklearn_predictions - onnx_predictions)

    predictions_equivalent = bool(
        np.allclose(sklearn_predictions, onnx_predictions, rtol=1e-5, atol=1e-5)
    )

    out_of_sample_status = "unknown"
    trained_until = artifact_metadata.get("trained_until")
    validation_from = validation_info.get("validation_from")
    if trained_until and validation_from:
        trained_until_ts = pd.Timestamp(trained_until)
        validation_from_ts = pd.Timestamp(validation_from)
        out_of_sample_status = (
            "yes" if trained_until_ts < validation_from_ts else "no_model_saw_validation_period"
        )

    report = {
        "source_model": str(args.model.resolve()),
        "onnx_model": str(args.output.resolve()),
        "target_opset": args.opset,
        "features_in_order": features,
        "target": target,
        "validation": validation_info,
        "out_of_sample_evaluation": out_of_sample_status,
        "artifact_metadata": artifact_metadata,
        "sklearn_metrics": sklearn_metrics,
        "onnx_metrics": onnx_metrics,
        "conversion_parity": {
            "predictions_equivalent_rtol_1e-5_atol_1e-5": predictions_equivalent,
            "max_absolute_prediction_delta_mw": float(absolute_prediction_delta.max()),
            "mean_absolute_prediction_delta_mw": float(absolute_prediction_delta.mean()),
            "mae_delta_mw": onnx_metrics["mae_mw"] - sklearn_metrics["mae_mw"],
            "rmse_delta_mw": onnx_metrics["rmse_mw"] - sklearn_metrics["rmse_mw"],
            "mape_delta_percentage_points": (
                onnx_metrics["mape_pct"] - sklearn_metrics["mape_pct"]
            ),
        },
        "onnx_interface": onnx_interface,
        "important_warning": (
            "Estas métricas solo representan desempeño fuera de muestra si el modelo "
            "exportado nunca fue entrenado con las filas del conjunto de validación."
        ),
    }

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(
        json.dumps(report, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print("\nMétricas scikit-learn")
    print(f"  MAE:  {sklearn_metrics['mae_mw']:.6f} MW")
    print(f"  RMSE: {sklearn_metrics['rmse_mw']:.6f} MW")
    print(f"  MAPE: {sklearn_metrics['mape_pct']:.6f} %")
    print("\nMétricas ONNX")
    print(f"  MAE:  {onnx_metrics['mae_mw']:.6f} MW")
    print(f"  RMSE: {onnx_metrics['rmse_mw']:.6f} MW")
    print(f"  MAPE: {onnx_metrics['mape_pct']:.6f} %")
    print("\nEquivalencia")
    print(f"  Predicciones equivalentes: {'sí' if predictions_equivalent else 'no'}")
    print(f"  Máxima diferencia: {absolute_prediction_delta.max():.10f} MW")
    if out_of_sample_status == "no_model_saw_validation_period":
        print(
            "\nADVERTENCIA: el modelo fue entrenado hasta una fecha incluida en la "
            "validación. Las métricas no son una medición honesta fuera de muestra; "
            "solo sirven para comparar scikit-learn con ONNX."
        )
    elif out_of_sample_status == "unknown":
        print(
            "\nADVERTENCIA: no se pudo confirmar si el modelo vio las filas de validación."
        )
    print(f"\nModelo ONNX: {args.output}")
    print(f"Reporte: {args.report}")

    if not predictions_equivalent and not args.allow_metric_drift:
        raise RuntimeError(
            "La conversión superó la tolerancia de equivalencia. "
            "Revise el reporte o use --allow-metric-drift solo si la diferencia es aceptable."
        )


if __name__ == "__main__":
    main()
